name: Benchmark
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  benchmark:
    name: Run redis-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Install Redis Tools
        run: sudo apt-get update && sudo apt-get install -y redis-tools

      - name: Start Server
        run: |
          ./target/release/rudisd --aof false &
          sleep 5

      - name: Run Benchmark
        run: |
          redis-benchmark -q -n 100000 -t ping > benchmark_output.txt

      - name: Convert benchmark to JSON
        run: |
          echo '[' > benchmark_output.json
          awk '/requests per second/ {
            gsub(/:/, "", $1);
            print "{\"name\":\"" $1 "\", \"value\": " $2 "},"
          }' benchmark_output.txt | sed '$ s/,$//' >> benchmark_output.json
          echo ']' >> benchmark_output.json

      - name: Check JSON
        run: cat benchmark_output.json

      - name: Store Benchmark Result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Redis Clone Performance
          tool: 'customBiggerIsBetter'
          output-file-path: benchmark_output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
          # alert if performance drops by more than 20%
          alert-threshold: '120%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@gxnda'
